### ISSUE TITLE
Document `prz` in the README

### ISSUE THREAD

**Issue by DanielVandH** [macd/BaryRational.jl#5]
Is `prz` part of the API? It would be nice to give an example of it in the docs if it is. A possible associated docstring could be:

```julia
"""
    prz(r::AAAapprox)

Return the poles, residues, and zeros of the AAA approximation r. 

!!! warning 

    If you are trying to use `aaa` with `BigFloat`s, make sure you have called 
    `aaa` with `clean=false` as, currently, `prz` is not generic.
"""
```

I have some examples where I use it for tracking complex singularities, but that's a bit much. I quite like the example for $f(z)=1/J_0(z)$ in Application 6.5 of https://people.maths.ox.ac.uk/trefethen/AAAfinal.pdf (see Figure 6.8). What do you think of the following example for the README? 

---

We also provide a function `prz` for extracting the poles, residues, and zeros from the AAA approximant. As an example, let us consider approximating $f(z) = 1/J_0(z)$ from random data in a rectangle in the complex plane, reproducing Figure 6.8 of [[1]](#ref1).

```julia
using BaryRational
using StableRNGs
using CairoMakie
using Bessels

## Setup the data
seed = 123
rng = StableRNG(123)
n = 2000
x = 10rand(rng, n)
y = 2rand(rng, n) .- 1
z = complex.(x, y)
f = z -> inv(besselj0(z))
fz = f.(z)

## Get the approximant and extract the poles and residues 
r = aaa(z, fz)
pol, res, zer = prz(r)

## Plot the error contours together with the data and computed poles
gridx = LinRange(-5, 15, 250)
gridy = LinRange(-3, 3, 250)
err = [abs(f(complex(x, y)) - r(complex(x, y))) for x in gridx, y in gridy]
fig = Figure()
ax = Axis(fig[1, 1], xlabel=L"x", ylabel=L"y", width=600, height=300)
contour!(ax, gridx, gridy, err, levels=10.0 .^ (-12:-1))
scatter!(ax, real(z), imag(z), color=:grey, markersize=4)
scatter!(ax, real(pol), imag(pol), color=:black, markersize=13)
xlims!(ax, -5, 15)
ylims!(ax, -3, 3)
resize_to_layout!(fig)
fig
```

![aaa_ex](https://github.com/macd/BaryRational.jl/assets/95613936/a04df782-496e-42ad-8048-8bba7347cace)

We see that the computed poles of the solution, shown as black dots, are all real, even though we imposed no symmetry in our initial data - an impressive feature of the AAA algorithm. Moreover, these black dots are almost exactly equal to the true poles of $f$, i.e. the zeros of $J_0(z)$, again showing the power of the algorithm. Some of the poles do have some imaginary parts, though:

```julia
fig = Figure()
ax = Axis(fig[1, 1], xlabel=L"x", ylabel=L"y", width=600, height=300)
sc = scatter!(ax, real(pol), imag(pol), markersize=13, color=abs.(res))
lines!(ax, [0, 10, 10, 0, 0], [-1, -1, 1, 1, -1], linewidth=3, color=:black)
Colorbar(fig[1, 2], sc, label="|res|")
resize_to_layout!(fig)
fig
```

![aaa_ex_poles](https://github.com/macd/BaryRational.jl/assets/95613936/a40d00f7-d3c6-40c1-8c4d-6290b662ad82)

Those that are away from the real line are far from the original domain of the data, though, or have small residues, as shown.

---

Just to make it easier for you, this is the original figure from the AAA paper:

![image](https://github.com/macd/BaryRational.jl/assets/95613936/658fb93e-b0bf-4490-af81-7bc9642aca8a)

**Comment by DanielVandH** [comment]
As an aside: What settings would you play around with to try and get the same error contours as in the figure in the paper?

**Comment by macd** [comment]
Yes, prz is a part of the public api, so I think this would be a good addition to the README.md (BTW, you have `seed = 123; rng = StableRNG(123)` where maybe you meant `seed = 123; rng = StableRNG(seed)` ?). So if you are up for it, another PR on the README would be great. As for more closely matching the AAA paper on this example, my guess is that it has to do with which random points are used to evaluate  the Bessel function because that in turn would dictate a different set of support points that the AAA algorithm would choose. Comparing the figures, it is interesting to see that the asymmetries in the error curve at 10^-12 are reversed and that the Julia based one seems to have a larger enclosed area for the 10^-12 error. But again, that is probably just the support points which are chosen out of a different random set of function evaluations.
